package chapter03.puzzle15;


/**
 * Generated by the IBM IDL-to-Java compiler, version 1.0
 * from F:\TestRoot\apps\a1\ units\include\PolicyHome.idl
 * Wednesday, June 17, 1998 6:44:40 o'clock AM GMT+00:00
 */

/*
in fact , there is no space between with \ and u :\TestRoot\apps\a1\ units\include\PolicyHome.idl
java: illegal unicode escape
 */

public class Test {
    public static void main(String[] args) {
        System.out.print("Hell");
        System.out.println("o world");
    }
}
